variables:
  PYTHON_VERSION: python
  STAGING: y

stages:
  - install
  - test
#  - deploy_test
#  - deploy_prod

.artifacts: &artifacts
  artifacts:
    paths:
      - .env/

.image_test: &image_test
  image: paradoxxxzero/python-node-yarn-postgresql:latest

install:
  stage: install
  <<: *image_test
  script:
    - make install
  <<: *artifacts

lint:
  stage: test
  <<: *image_test
  script:
    - make lint
  dependencies:
    - install

test:
  stage: test
  <<: *image_test
  script:
    - make check
  dependencies:
    - install


.image: &image_deploy_jobs
  image: debian:latest

#deploy_test:
#  <<: *image_deploy_jobs
#  stage: deploy_test
#  before_script:
#    - apt-get update && apt-get install -y wget make
#  script:
#    - make deploy-test
#  dependencies: []

#deploy_prod:
#  <<: *image_deploy_jobs
#  stage: deploy_prod
#  before_script:
#    - apt-get update && apt-get install -y wget make
#  script:
#    - make deploy-prod
#  dependencies: []
#  only:
#    - master
